<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
class CountryTableSeeder extends Seeder {

	public function run()
	{
        $countries = [
            ['title' => 'أندورا','code' => 'ad'],
            ['title' => 'الإمارات العربية المتحدة','code' => 'ae'],
            ['title' => 'أفغانستان','code' => 'af'],
            ['title' => 'أنتيغوا وبربودا','code' => 'ag'],
            ['title' => 'أنغيلا','code' => 'ai'],
            ['title' => 'ألبانيا','code' => 'al'],
            ['title' => 'أرمينيا','code' => 'am'],
            ['title' => 'جزر الأنتيل الهولندية','code' => 'an'],
            ['title' => 'أنغولا','code' => 'ao'],
            ['title' => 'الأرجنتين','code' => 'ar'],
            ['title' => 'النمسا','code' => 'at'],
            ['title' => 'أستراليا','code' => 'au'],
            ['title' => 'أروبا','code' => 'aw'],
            ['title' => 'أذربيجان','code' => 'az'],
            ['title' => 'البوسنة والهرسك','code' => 'ba'],
            ['title' => 'بربادوس','code' => 'bb'],
            ['title' => 'بنغلاديش','code' => 'bd'],
            ['title' => 'بلجيكا','code' => 'be'],
            ['title' => 'بوركينا فاسو','code' => 'bf'],
            ['title' => 'بلغاريا','code' => 'bg'],
            ['title' => 'البحرين','code' => 'bh'],
            ['title' => 'بوروندي','code' => 'bi'],
            ['title' => 'بنين','code' => 'bj'],
            ['title' => 'برمودا','code' => 'bm'],
            ['title' => 'بروناي دار السلام','code' => 'bn'],
            ['title' => 'بوليفيا','code' => 'bo'],
            ['title' => 'البرازيل','code' => 'br'],
            ['title' => 'الباهاما','code' => 'bs'],
            ['title' => 'بوتان','code' => 'bt'],
            ['title' => 'بوتسوانا','code' => 'bw'],
            ['title' => 'روسيا البيضاء','code' => 'by'],
            ['title' => 'بليز','code' => 'bz'],
            ['title' => 'كندا','code' => 'ca'],
            ['title' => 'جزر كوكوس (كيلينغ)','code' => 'cc'],
            ['title' => 'جمهورية الكونغو الديموقراطية','code' => 'cd'],
            ['title' => 'جمهورية افريقيا الوسطى','code' => 'cf'],
            ['title' => 'الكونغو','code' => 'cg'],
            ['title' => 'سويسرا','code' => 'ch'],
            ['title' => 'ساحل العاج (ساحل العاج)','code' => 'ci'],
            ['title' => 'جزر كوك','code' => 'ck'],
            ['title' => 'تشيلي','code' => 'cl'],
            ['title' => 'الكاميرون','code' => 'cm'],
            ['title' => 'الصين','code' => 'cn'],
            ['title' => 'كولومبيا','code' => 'co'],
            ['title' => 'كوستا ريكا','code' => 'cr'],
            ['title' => 'كوبا','code' => 'cu'],
            ['title' => 'الرأس الأخضر','code' => 'cv'],
            ['title' => 'جزيرة الكريسماس','code' => 'cx'],
            ['title' => 'قبرص','code' => 'cy'],
            ['title' => 'جمهورية التشيك','code' => 'cz'],
            ['title' => 'ألمانيا','code' => 'de'],
            ['title' => 'جيبوتي','code' => 'dj'],
            ['title' => 'الدنمارك','code' => 'dk'],
            ['title' => 'دومينيكا','code' => 'dm'],
            ['title' => 'جمهورية الدومنيكان','code' => 'do'],
            ['title' => 'الجزائر','code' => 'dz'],
            ['title' => 'الإكوادور','code' => 'ec'],
            ['title' => 'استونيا','code' => 'ee'],
            ['title' => 'مصر','code' => 'eg'],
            ['title' => 'الصحراء الغربية','code' => 'eh'],
            ['title' => 'إريتريا','code' => 'er'],
            ['title' => 'إسبانيا','code' => 'es'],
            ['title' => 'أثيوبيا','code' => 'et'],
            ['title' => 'فنلندا','code' => 'fi'],
            ['title' => 'فيجي','code' => 'fj'],
            ['title' => 'جزر فوكلاند (مالفيناس)','code' => 'fk'],
            ['title' => 'ولايات ميكرونيزيا الموحدة','code' => 'fm'],
            ['title' => 'جزر صناعية','code' => 'fo'],
            ['title' => 'فرنسا','code' => 'fr'],
            ['title' => 'الغابون','code' => 'ga'],
            ['title' => 'بريطانيا العظمى (المملكة المتحدة)','code' => 'gb'],
            ['title' => 'غرينادا','code' => 'gd'],
            ['title' => 'جورجيا','code' => 'ge'],
            ['title' => 'غيانا الفرنسية','code' => 'gf'],
            ['title' => 'لا شيء','code' => 'gg'],
            ['title' => 'غانا','code' => 'gh'],
            ['title' => 'جبل طارق','code' => 'gi'],
            ['title' => 'الأرض الخضراء','code' => 'gl'],
            ['title' => 'غامبيا','code' => 'gm'],
            ['title' => 'غينيا','code' => 'gn'],
            ['title' => 'جوادلوب','code' => 'gp'],
            ['title' => 'غينيا الإستوائية','code' => 'gq'],
            ['title' => 'اليونان','code' => 'gr'],
            ['title' => 'جورجيا وجزر ساندويتش','code' => 'gs'],
            ['title' => 'غواتيمالا','code' => 'gt'],
            ['title' => 'غينيا بيساو','code' => 'gw'],
            ['title' => 'غيانا','code' => 'gy'],
            ['title' => 'هونغ كونغ','code' => 'hk'],
            ['title' => 'هندوراس','code' => 'hn'],
            ['title' => 'كرواتيا (هرفاتسكا)','code' => 'hr'],
            ['title' => 'هايتي','code' => 'ht'],
            ['title' => 'اليونان','code' => 'hu'],
            ['title' => 'أندونيسيا','code' => 'id'],
            ['title' => 'أيرلندا','code' => 'ie'],
            ['title' => 'الهند','code' => 'in'],
            ['title' => 'العراق','code' => 'iq'],
            ['title' => 'إيران','code' => 'ir'],
            ['title' => 'أيسلندا','code' => 'is'],
            ['title' => 'إيطاليا','code' => 'it'],
            ['title' => 'جامايكا','code' => 'jm'],
            ['title' => 'الأردن','code' => 'jo'],
            ['title' => 'اليابان','code' => 'jp'],
            ['title' => 'كينيا','code' => 'ke'],
            ['title' => 'قرغيزستان','code' => 'kg'],
            ['title' => 'كمبوديا','code' => 'kh'],
            ['title' => 'كيريباس','code' => 'ki'],
            ['title' => 'جزر القمر','code' => 'km'],
            ['title' => 'سانت كيتس ونيفيس','code' => 'kn'],
            ['title' => 'كوريا الشمالية','code' => 'kp'],
            ['title' => 'كوريا، جنوب)','code' => 'kr'],
            ['title' => 'الكويت','code' => 'kw'],
            ['title' => 'جزر كايمان','code' => 'ky'],
            ['title' => 'كازاخستان','code' => 'kz'],
            ['title' => 'لاوس','code' => 'la'],
            ['title' => 'لبنان','code' => 'lb'],
            ['title' => 'القديسة لوسيا','code' => 'lc'],
            ['title' => 'ليختنشتاين','code' => 'li'],
            ['title' => 'سيريلانكا','code' => 'lk'],
            ['title' => 'ليبيريا','code' => 'lr'],
            ['title' => 'ليسوتو','code' => 'ls'],
            ['title' => 'ليتوانيا','code' => 'lt'],
            ['title' => 'لوكسمبورغ','code' => 'lu'],
            ['title' => 'لاتفيا','code' => 'lv'],
            ['title' => 'ليبيا','code' => 'ly'],
            ['title' => 'المغرب','code' => 'ma'],
            ['title' => 'موناكو','code' => 'mc'],
            ['title' => 'مولدوفا','code' => 'md'],
            ['title' => 'مدغشقر','code' => 'mg'],
            ['title' => 'جزر مارشال','code' => 'mh'],
            ['title' => 'مقدونيا','code' => 'mk'],
            ['title' => 'مالي','code' => 'ml'],
            ['title' => 'ميانمار','code' => 'mm'],
            ['title' => 'منغوليا','code' => 'mn'],
            ['title' => 'ماكاو','code' => 'mo'],
            ['title' => 'جزر مريانا الشمالية','code' => 'mp'],
            ['title' => 'مارتينيك','code' => 'mq'],
            ['title' => 'موريتانيا','code' => 'mr'],
            ['title' => 'مونتسيرات','code' => 'ms'],
            ['title' => 'مالطا','code' => 'mt'],
            ['title' => 'موريشيوس','code' => 'mu'],
            ['title' => 'جزر المالديف','code' => 'mv'],
            ['title' => 'مالاوي','code' => 'mw'],
            ['title' => 'المكسيك','code' => 'mx'],
            ['title' => 'ماليزيا','code' => 'my'],
            ['title' => 'موزمبيق','code' => 'mz'],
            ['title' => 'ناميبيا','code' => 'na'],
            ['title' => 'كاليدونيا الجديدة','code' => 'nc'],
            ['title' => 'النيجر','code' => 'ne'],
            ['title' => 'جزيرة نورفولك','code' => 'nf'],
            ['title' => 'نيجيريا','code' => 'ng'],
            ['title' => 'نيكاراغوا','code' => 'ni'],
            ['title' => 'هولندا','code' => 'nl'],
            ['title' => 'النرويج','code' => 'no'],
            ['title' => 'نيبال','code' => 'np'],
            ['title' => 'ناورو','code' => 'nr'],
            ['title' => 'نيوي','code' => 'nu'],
            ['title' => 'نيوزيلندا (اوتياروا)','code' => 'nz'],
            ['title' => 'سلطنة عمان','code' => 'om'],
            ['title' => 'بناما','code' => 'pa'],
            ['title' => 'بيرو','code' => 'pe'],
            ['title' => 'بولينيزيا الفرنسية','code' => 'pf'],
            ['title' => 'بابوا غينيا الجديدة','code' => 'pg'],
            ['title' => 'الفلبين','code' => 'ph'],
            ['title' => 'باكستان','code' => 'pk'],
            ['title' => 'بولندا','code' => 'pl'],
            ['title' => 'سانت بيير وميكلون','code' => 'pm'],
            ['title' => 'بيتكيرن','code' => 'pn'],
            ['title' => 'الأراضي الفلسطينية','code' => 'ps'],
            ['title' => 'البرتغال','code' => 'pt'],
            ['title' => 'بالاو','code' => 'pw'],
            ['title' => 'باراغواي','code' => 'py'],
            ['title' => 'دولة قطر','code' => 'qa'],
            ['title' => 'جمع شمل','code' => 're'],
            ['title' => 'رومانيا','code' => 'ro'],
            ['title' => 'الاتحاد الروسي','code' => 'ru'],
            ['title' => 'رواندا','code' => 'rw'],
            ['title' => 'المملكة العربية السعودية','code' => 'sa'],
            ['title' => 'جزر سليمان','code' => 'sb'],
            ['title' => 'سيشيل','code' => 'sc'],
            ['title' => 'سودان','code' => 'sd'],
            ['title' => 'السويد','code' => 'se'],
            ['title' => 'سنغافورة','code' => 'sg'],
            ['title' => 'سانت هيلانة','code' => 'sh'],
            ['title' => 'سلوفينيا','code' => 'si'],
            ['title' => 'سفالبارد وجان مايان','code' => 'sj'],
            ['title' => 'سلوفاكيا','code' => 'sk'],
            ['title' => 'سيرا ليون','code' => 'sl'],
            ['title' => 'سان مارينو','code' => 'sm'],
            ['title' => 'السنغال','code' => 'sn'],
            ['title' => 'الصومال','code' => 'so'],
            ['title' => 'سورينام','code' => 'sr'],
            ['title' => 'ساو تومي وبرنسيبي','code' => 'st'],
            ['title' => 'السلفادور','code' => 'sv'],
            ['title' => 'سوريا','code' => 'sy'],
            ['title' => 'سوازيلاند','code' => 'sz'],
            ['title' => 'جزر تركس وكايكوس','code' => 'tc'],
            ['title' => 'تشاد','code' => 'td'],
            ['title' => 'المناطق الجنوبية لفرنسا','code' => 'tf'],
            ['title' => 'ليذهب','code' => 'tg'],
            ['title' => 'تايلاند','code' => 'th'],
            ['title' => 'طاجيكستان','code' => 'tj'],
            ['title' => 'توكيلاو','code' => 'tk'],
            ['title' => 'تركمانستان','code' => 'tm'],
            ['title' => 'تونس','code' => 'tn'],
            ['title' => 'تونغا','code' => 'to'],
            ['title' => 'ديك رومي','code' => 'tr'],
            ['title' => 'ترينداد وتوباغو','code' => 'tt'],
            ['title' => 'توفالو','code' => 'tv'],
            ['title' => 'تايوان','code' => 'tw'],
            ['title' => 'تنزانيا','code' => 'tz'],
            ['title' => 'أوكرانيا','code' => 'ua'],
            ['title' => 'أوغندا','code' => 'ug'],
            ['title' => 'أوروغواي','code' => 'uy'],
            ['title' => 'أوزبكستان','code' => 'uz'],
            ['title' => 'سانت فنسنت وجزر غرينادين','code' => 'vc'],
            ['title' => 'فنزويلا','code' => 've'],
            ['title' => 'جزر العذراء البريطانية)','code' => 'vg'],
            ['title' => 'جزر فيرجن (الولايات المتحدة)','code' => 'vi'],
            ['title' => 'فيتنام','code' => 'vn'],
            ['title' => 'فانواتو','code' => 'vu'],
            ['title' => 'واليس وفوتونا','code' => 'wf'],
            ['title' => 'ساموا','code' => 'ws'],
            ['title' => 'اليمن','code' => 'ye'],
            ['title' => 'مايوت','code' => 'yt'],
            ['title' => 'جنوب أفريقيا','code' => 'za'],
            ['title' => 'زامبيا','code' => 'zm'],
            ['title' => 'زائير (سابقة)','code' => 'zr'],
            ['title' => 'زيمبابوي','code' => 'zw'],
            ['title' => 'الولايات المتحدة','code' => 'us'],
        
            ];

            DB::table('countries')->insert($countries);
    }

}