<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
class RegionCityDistrictSeeder extends Seeder
{
    public function run()
    {
        $regions = [['title' => 'القصيم', 'country_id' => '177'], ['title' => 'الباحة', 'country_id' => '177'], ['title' => 'الحدود الشمالية', 'country_id' => '177'], ['title' => 'الرياض', 'country_id' => '177'], ['title' => 'عسير', 'country_id' => '177'], ['title' => 'تبوك', 'country_id' => '177'], ['title' => 'المدينة المنورة', 'country_id' => '177'], ['title' => 'الجوف', 'country_id' => '177'], ['title' => 'نجران', 'country_id' => '177'], ['title' => ' جازان', 'country_id' => '177'], ['title' => 'حائل', 'country_id' => '177'], ['title' => 'المنطقة الشرقية', 'country_id' => '177'], ['title' => 'منطقة مكة المكرمة', 'country_id' => '177']];

        DB::table('regions')->insert($regions);
        ///////////////////////////////////////////////////////////////////
        $cities = [
            ['title' => 'بريدة', 'region_id' => '1'],
            ['title' => 'الباحة', 'region_id' => '2'],
            ['title' => 'العويقلية', 'region_id' => '3'],
            ['title' => 'رفحاء', 'region_id' => '3'],
            ['title' => 'عرعر', 'region_id' => '3'],
            ['title' => 'قرية جديدة عرعر', 'region_id' => '3'],
            ['title' => 'قرية حزم الجلاميد', 'region_id' => '3'],
            ['title' => 'هجرة الهبكة', 'region_id' => '3'],
            ['title' => 'هجرة رغوه', 'region_id' => '3'],
            ['title' => 'هجرة اعيوج', 'region_id' => '3'],
            ['title' => 'هجرة العجرميه', 'region_id' => '3'],
            ['title' => 'هجرة نعيجيان', 'region_id' => '3'],
            ['title' => 'هجرة الايديه', 'region_id' => '3'],
            ['title' => 'هجرة لوقه', 'region_id' => '3'],
            ['title' => 'هجرة الدويد', 'region_id' => '3'],
            ['title' => 'هجرة ام رضمة', 'region_id' => '3'],
            ['title' => 'هجرة قليب بن غنيم', 'region_id' => '3'],
            ['title' => 'هجرة الحدقة', 'region_id' => '3'],
            ['title' => 'هجرة القصوريات', 'region_id' => '3'],
            ['title' => 'هجرة ابن بكر', 'region_id' => '3'],
            ['title' => 'هجرة اب سعيد', 'region_id' => '3'],
            ['title' => 'قرية طلعة التمياط', 'region_id' => '3'],
            ['title' => 'هجرة الجبهان', 'region_id' => '3'],
            ['title' => 'هجرة دغيليب الوجعان', 'region_id' => '3'],
            ['title' => 'هجرة ابن عايش', 'region_id' => '3'],
            ['title' => 'قرية السليمانية', 'region_id' => '3'],
            ['title' => 'هجرة الديدب', 'region_id' => '3'],
            ['title' => 'هجرة ام خنصر', 'region_id' => '3'],
            ['title' => 'هجرة ام الضيان', 'region_id' => '3'],
            ['title' => 'هجرة لينة', 'region_id' => '3'],
            ['title' => 'هجرة الخشيبي', 'region_id' => '3'],
            ['title' => 'هجرة المركوز', 'region_id' => '3'],
            ['title' => 'روضة ابن هباس', 'region_id' => '3'],
            ['title' => 'قرية شعبة نصاب', 'region_id' => '3'],
            ['title' => 'شقراء', 'region_id' => '4'],
            ['title' => 'أبها', 'region_id' => '5'],
            ['title' => 'خميس مشيط', 'region_id' => '5'],
            ['title' => 'تبوك', 'region_id' => '6'],
            ['title' => 'رماح', 'region_id' => '4'],
            ['title' => 'بني حسن', 'region_id' => '2'],
            ['title' => 'نوان', 'region_id' => '2'],
            ['title' => 'طبرجل', 'region_id' => '8'],
            ['title' => 'دومة الجندل', 'region_id' => '8'],
            ['title' => 'القريات', 'region_id' => '8'],
            ['title' => 'وادي كروان السويدي', 'region_id' => '2'],
            ['title' => 'وادي ريم', 'region_id' => '2'],
            ['title' => 'وادي الحضن السودي', 'region_id' => '2'],
            ['title' => 'غامد الزناد', 'region_id' => '2'],
            ['title' => 'الصفاردة', 'region_id' => '2'],
            ['title' => 'الشوق', 'region_id' => '2'],
            ['title' => 'الشعراء', 'region_id' => '2'],
            ['title' => 'الحلاة', 'region_id' => '2'],
            ['title' => 'الحجرة', 'region_id' => '2'],
            ['title' => 'القرى', 'region_id' => '2'],
            ['title' => 'قلوة', 'region_id' => '2'],
            ['title' => 'العقيق', 'region_id' => '2'],
            ['title' => 'المخواة', 'region_id' => '2'],
            ['title' => 'المندق', 'region_id' => '2'],
            ['title' => 'بلجرشي', 'region_id' => '2'],
            ['title' => 'شرورة', 'region_id' => '9'],
            ['title' => 'خباش', 'region_id' => '9'],
            ['title' => 'حبونا', 'region_id' => '9'],
            ['title' => 'ثار', 'region_id' => '9'],
            ['title' => 'بدر الجنوب', 'region_id' => '9'],
            ['title' => 'عتود', 'region_id' => '10'],
            ['title' => 'الشقيق', 'region_id' => '10'],
            ['title' => 'السادلية', 'region_id' => '10'],
            ['title' => 'الأثلية', 'region_id' => '10'],
            ['title' => 'هروب', 'region_id' => '10'],
            ['title' => 'ضمد', 'region_id' => '10'],
            ['title' => 'صامطة', 'region_id' => '10'],
            ['title' => 'بيش', 'region_id' => '10'],
            ['title' => 'العيدابي', 'region_id' => '10'],
            ['title' => 'العارضة', 'region_id' => '10'],
            ['title' => 'الطوال', 'region_id' => '10'],
            ['title' => 'الريث', 'region_id' => '10'],
            ['title' => 'الدرب', 'region_id' => '10'],
            ['title' => 'الدائر', 'region_id' => '10'],
            ['title' => 'الحرث', 'region_id' => '10'],
            ['title' => 'أحد المسارحة', 'region_id' => '10'],
            ['title' => 'فيفا', 'region_id' => '10'],
            ['title' => 'جزر فرسان', 'region_id' => '10'],
            ['title' => 'أبو عريش', 'region_id' => '10'],
            ['title' => 'قفار', 'region_id' => '11'],
            ['title' => 'الشنان', 'region_id' => '11'],
            ['title' => 'سميراء', 'region_id' => '11'],
            ['title' => 'مسجد لبدة', 'region_id' => '11'],
            ['title' => 'الحائط', 'region_id' => '11'],
            ['title' => 'جبة', 'region_id' => '11'],
            ['title' => 'ثويليل', 'region_id' => '11'],
            ['title' => 'بقعاء', 'region_id' => '11'],
            ['title' => 'النحيتية', 'region_id' => '11'],
            ['title' => 'تربة', 'region_id' => '11'],
            ['title' => 'القاعد', 'region_id' => '11'],
            ['title' => 'الغزالة', 'region_id' => '11'],
            ['title' => 'الشملي', 'region_id' => '11'],
            ['title' => 'الروضة', 'region_id' => '11'],
            ['title' => 'الحفير', 'region_id' => '11'],
            ['title' => 'البدع', 'region_id' => '6'],
            ['title' => 'تيماء', 'region_id' => '6'],
            ['title' => 'حقل', 'region_id' => '6'],
            ['title' => 'أملج', 'region_id' => '6'],
            ['title' => 'ضباء', 'region_id' => '6'],
            ['title' => 'الوجه', 'region_id' => '6'],
            ['title' => 'الربوعة', 'region_id' => '5'],
            ['title' => 'وادي بن هشبل', 'region_id' => '5'],
            ['title' => 'مركز بللحمر', 'region_id' => '5'],
            ['title' => 'محايل عسير', 'region_id' => '5'],
            ['title' => 'تثليث', 'region_id' => '5'],
            ['title' => 'بيشة', 'region_id' => '5'],
            ['title' => 'قنا', 'region_id' => '5'],
            ['title' => 'قصر ذهبان', 'region_id' => '5'],
            ['title' => 'عبس', 'region_id' => '5'],
            ['title' => 'ظهران الجنوب', 'region_id' => '5'],
            ['title' => 'سراة عبيدة', 'region_id' => '5'],
            ['title' => 'سبت العلاية', 'region_id' => '5'],
            ['title' => 'خاط', 'region_id' => '5'],
            ['title' => 'حجلا', 'region_id' => '5'],
            ['title' => 'تنومة', 'region_id' => '5'],
            ['title' => 'تندحة', 'region_id' => '5'],
            ['title' => 'بللسمر', 'region_id' => '5'],
            ['title' => 'بارق', 'region_id' => '5'],
            ['title' => 'باحة ربيعة', 'region_id' => '5'],
            ['title' => 'القوباء', 'region_id' => '5'],
            ['title' => 'الحرجة', 'region_id' => '5'],
            ['title' => 'البرك', 'region_id' => '5'],
            ['title' => 'أحد ثربان', 'region_id' => '5'],
            ['title' => 'آلفصيل', 'region_id' => '5'],
            ['title' => 'ختبة', 'region_id' => '5'],
            ['title' => 'عقلة الصقور', 'region_id' => '1'],
            ['title' => 'ضرية', 'region_id' => '1'],
            ['title' => 'حرب الجلاس', 'region_id' => '1'],
            ['title' => 'الشماسية', 'region_id' => '1'],
            ['title' => 'رياض الخبراء', 'region_id' => '1'],
            ['title' => 'عيون الجواء', 'region_id' => '1'],
            ['title' => 'النبهانية', 'region_id' => '1'],
            ['title' => 'الأسياح', 'region_id' => '1'],
            ['title' => 'البدائع', 'region_id' => '1'],
            ['title' => 'البكرية', 'region_id' => '1'],
            ['title' => 'المذنب', 'region_id' => '1'],
            ['title' => 'العيص', 'region_id' => '7'],
            ['title' => 'وادي الفرع', 'region_id' => '7'],
            ['title' => 'أم المخاييل', 'region_id' => '7'],
            ['title' => 'مهد الذهب', 'region_id' => '7'],
            ['title' => 'خيبر', 'region_id' => '7'],
            ['title' => 'العلا', 'region_id' => '7'],
            ['title' => 'قرية العليا', 'region_id' => '12'],
            ['title' => 'القطيف', 'region_id' => '12'],
            ['title' => 'العديد', 'region_id' => '12'],
            ['title' => 'الخفجي', 'region_id' => '12'],
            ['title' => 'بقيق', 'region_id' => '12'],
            ['title' => 'النعيرية', 'region_id' => '12'],
            ['title' => 'سيهات', 'region_id' => '12'],
            ['title' => 'رأس تنورة', 'region_id' => '12'],
            ['title' => 'الهفوف', 'region_id' => '12'],
            ['title' => 'القيصومة', 'region_id' => '12'],
            ['title' => 'العيون', 'region_id' => '12'],
            ['title' => 'ميسان', 'region_id' => '13'],
            ['title' => 'مستورة', 'region_id' => '13'],
            ['title' => 'العرضيات', 'region_id' => '13'],
            ['title' => 'مركز كنانة', 'region_id' => '13'],
            ['title' => 'رنية', 'region_id' => '13'],
            ['title' => 'دوقة', 'region_id' => '13'],
            ['title' => 'خليص', 'region_id' => '13'],
            ['title' => 'حلي', 'region_id' => '13'],
            ['title' => 'ثريبان العرضيات', 'region_id' => '13'],
            ['title' => 'ثربان', 'region_id' => '13'],
            ['title' => 'بلدة الحبيل', 'region_id' => '13'],
            ['title' => 'بحرة', 'region_id' => '13'],
            ['title' => 'الهداء', 'region_id' => '13'],
            ['title' => 'الموية', 'region_id' => '13'],
            ['title' => 'المضيلف', 'region_id' => '13'],
            ['title' => 'الليث', 'region_id' => '13'],
            ['title' => 'الكامل', 'region_id' => '13'],
            ['title' => 'القنفذة', 'region_id' => '13'],
            ['title' => 'القوز', 'region_id' => '13'],
            ['title' => 'الغالة', 'region_id' => '13'],
            ['title' => 'الصهوة', 'region_id' => '13'],
            ['title' => 'السعدية', 'region_id' => '13'],
            ['title' => 'الخرمة', 'region_id' => '13'],
            ['title' => 'الحوية', 'region_id' => '4'],
            ['title' => 'البيضاء', 'region_id' => '13'],
            ['title' => 'أضم', 'region_id' => '13'],
            ['title' => 'أحد بني زايد', 'region_id' => '13'],
            ['title' => 'حوطة سدير', 'region_id' => '4'],
            ['title' => 'تمير', 'region_id' => '4'],
            ['title' => 'الحلوة', 'region_id' => '4'],
            ['title' => 'المزاحمية', 'region_id' => '4'],
            ['title' => 'السليل', 'region_id' => '4'],
            ['title' => 'روضة سدير', 'region_id' => '4'],
            ['title' => 'وادي الدواسر', 'region_id' => '4'],
            ['title' => 'مرات', 'region_id' => '4'],
            ['title' => 'الدلم', 'region_id' => '4'],
            ['title' => 'ثادق', 'region_id' => '4'],
            ['title' => 'جلاجل', 'region_id' => '4'],
            ['title' => 'ظرما', 'region_id' => '4'],
            ['title' => 'حوطة بني تميم', 'region_id' => '4'],
            ['title' => 'الزلفي', 'region_id' => '4'],
            ['title' => 'الفاط', 'region_id' => '4'],
            ['title' => 'المجمعة', 'region_id' => '4'],
            ['title' => 'الرس', 'region_id' => '1'],
            ['title' => 'جازان', 'region_id' => '10'],
            ['title' => 'الرياض', 'region_id' => '4'],
            ['title' => 'الدمام', 'region_id' => '12'],
            ['title' => 'الأحساء', 'region_id' => '12'],
            ['title' => 'الخبر', 'region_id' => '12'],
            ['title' => 'الطائف', 'region_id' => '13'],
            ['title' => 'ينبع', 'region_id' => '7'],
            ['title' => 'الدوادمي', 'region_id' => '4'],
            ['title' => 'الخرج', 'region_id' => '4'],
            ['title' => 'صبيا', 'region_id' => '10'],
            ['title' => 'طريف', 'region_id' => '3'],
            ['title' => 'عنيزة', 'region_id' => '1'],
            ['title' => 'حفر الباطن', 'region_id' => '12'],
            ['title' => 'سكاكا', 'region_id' => '8'],
            ['title' => 'حائل', 'region_id' => '11'],
            ['title' => 'نجران', 'region_id' => '9'],
            ['title' => 'المدينة المنورة', 'region_id' => '7'],
            ['title' => 'العاصمة المقدسة', 'region_id' => '13'],
            ['title' => 'جدة', 'region_id' => '13'],
            ['title' => 'الجبيل', 'region_id' => '12'],
            ['title' => 'أحد رفيدة', 'region_id' => '5'],
            ['title' => 'الذيبية', 'region_id' => '12'],
            ['title' => 'الظهران', 'region_id' => '12'],
            ['title' => 'الجموم', 'region_id' => '13'],
            ['title' => 'اخرى', 'region_id' => '5'],
            ['title' => 'مدينة صبياء', 'region_id' => '10'],
        ];
        DB::table('cities')->insert($cities);

        ////////////////////

        $districts = [
            ['title'=>'رواق','city_id'=>'1'],
            ['title'=>'المصيف','city_id'=>'3'],
            ['title'=>'الورود','city_id'=>'3'],
            ['title'=>'الصناعية','city_id'=>'3'],
            ['title'=>'البلدة القديمة','city_id'=>'3'],
            ['title'=>'النسيم','city_id'=>'3'],
            ['title'=>'المنار <ج>','city_id'=>'3'],
            ['title'=>'الاندلس','city_id'=>'3'],
            ['title'=>'الروضة','city_id'=>'3'],
            ['title'=>'الخليج','city_id'=>'3'],
            ['title'=>'الامير سلطان','city_id'=>'3'],
            ['title'=>'طويريق','city_id'=>'3'],
            ['title'=>'اسكان الملك عبدالله','city_id'=>'3'],
            ['title'=>'الصالحية','city_id'=>'3'],
            ['title'=>'قرية جديدة عرعر','city_id'=>'3'],
            ['title'=>'قرية حزم الجلاميد','city_id'=>'3'],
            ['title'=>'هجرة الهبكة','city_id'=>'3'],
            ['title'=>'هجرة رغوه','city_id'=>'3'],
            ['title'=>'هجرة اعيوج','city_id'=>'3'],
            ['title'=>'هجرة العجرميه','city_id'=>'3'],
            ['title'=>'هجرة نعيجيان','city_id'=>'3'],
            ['title'=>'هجرة الايديه','city_id'=>'3'],
            ['title'=>'هجرة لوقه','city_id'=>'3'],
            ['title'=>'هجرة الدويد','city_id'=>'3'],
            ['title'=>'هجرة ام رضمة','city_id'=>'3'],
            ['title'=>'هجرة قليب بن غنيم','city_id'=>'3'],
            ['title'=>'هجرة الحدقة','city_id'=>'3'],
            ['title'=>'هجرة القصوريات','city_id'=>'3'],
            ['title'=>'هجرة ابن بكر','city_id'=>'3'],
            ['title'=>'هجرة ابن سعيد','city_id'=>'3'],
            ['title'=>'قرية طلعة التمياط','city_id'=>'3'],
            ['title'=>'هجرة الجبهان','city_id'=>'3'],
            ['title'=>'هجرة دغيليب الوجعان','city_id'=>'3'],
            ['title'=>'هجرة ابن عايش','city_id'=>'3'],
            ['title'=>'قرية السليمانية','city_id'=>'3'],
            ['title'=>'هجرة الديدب','city_id'=>'3'],
            ['title'=>'هجرة ام خنصر','city_id'=>'3'],
            ['title'=>'هجرة ام الضيان','city_id'=>'3'],
            ['title'=>'هجرة لينة','city_id'=>'3'],
            ['title'=>'هجرة الخشيبي','city_id'=>'3'],
            ['title'=>'هجرة المركوز','city_id'=>'3'],
            ['title'=>'روضة ابن هباس','city_id'=>'3'],
            ['title'=>'قرية شعبة نصاب','city_id'=>'3'],
            ['title'=>'شقراء','city_id'=>'4'],
            ['title'=>'الطبجيه','city_id'=>'5'],
            ['title'=>'شمسان','city_id'=>'5'],
            ['title'=>'السد','city_id'=>'5'],
            ['title'=>'العزيزية','city_id'=>'5'],
            ['title'=>'الوردتين','city_id'=>'5'],
            ['title'=>'الوصايف','city_id'=>'5'],
            ['title'=>'الربوة','city_id'=>'5'],
            ['title'=>'النزهة','city_id'=>'5'],
            ['title'=>'النزهة','city_id'=>'5'],
            ['title'=>'الخشع','city_id'=>'5'],
            ['title'=>'الخالدية','city_id'=>'5'],
            ['title'=>'مدينة سلطان','city_id'=>'2'],
            ['title'=>'المحالة','city_id'=>'5'],
            ['title'=>'المنسك','city_id'=>'5'],
            ['title'=>'النميص','city_id'=>'5'],
            ['title'=>'الرونة','city_id'=>'5'],
            ['title'=>'الهرير','city_id'=>'5'],
            ['title'=>'شباعه','city_id'=>'5'],
            ['title'=>'حسام','city_id'=>'5'],
            ['title'=>'طيب الاسم','city_id'=>'5'],
            ['title'=>'الشرفية','city_id'=>'5'],
            ['title'=>'الرصراص','city_id'=>'5'],
            ['title'=>'ضاحية الملك فهد','city_id'=>'3'],
            ['title'=>'الروضة','city_id'=>'3'],
            ['title'=>'الروابي','city_id'=>'3'],
            ['title'=>'غرناطة','city_id'=>'3'],
            ['title'=>'قرطبة','city_id'=>'3'],
            ['title'=>'العامرية','city_id'=>'6'],
            ['title'=>'الحمراء','city_id'=>'6'],
            ['title'=>'العليا','city_id'=>'6'],
            ['title'=>'النظيم','city_id'=>'6'],
            ['title'=>'الاندلس','city_id'=>'6'],
            ['title'=>'العمال','city_id'=>'3'],
            ['title'=>'الورود','city_id'=>'3'],
            ['title'=>'الاسكان','city_id'=>'3'],
            ['title'=>'حمراء الأسد','city_id'=>'7'],
            ['title'=>'التلال','city_id'=>'7'],
            ['title'=>'رماح','city_id'=>'4'],
            ['title'=>'وسط المدينة','city_id'=>'2'],
            ['title'=>'بني حسن','city_id'=>'2'],
            ['title'=>'نوان','city_id'=>'2'],
            ['title'=>'طبرجل','city_id'=>'8'],
            ['title'=>'القريات','city_id'=>'8'],
            ['title'=>'دومة الجندل','city_id'=>'8'],
            ['title'=>'وادي كروان السويدي','city_id'=>'2'],
            ['title'=>'وادي ريم','city_id'=>'2'],
            ['title'=>'وادي الحضن السودي','city_id'=>'2'],
            ['title'=>'غامد الزناد','city_id'=>'2'],
            ['title'=>'بني حسن','city_id'=>'2'],
            ['title'=>'الصفاردة','city_id'=>'2'],
            ['title'=>'الصفاردة','city_id'=>'2'],
            ['title'=>'الشوق','city_id'=>'2'],
            ['title'=>'الشعراء','city_id'=>'2'],
            ['title'=>'الحلاة','city_id'=>'2'],
            ['title'=>'الحجرة','city_id'=>'2'],
            ['title'=>'القرى','city_id'=>'2'],
            ['title'=>'قلوة','city_id'=>'2'],
            ['title'=>'العقيق','city_id'=>'2'],
            ['title'=>'المخواة','city_id'=>'2'],
            ['title'=>'المندق','city_id'=>'2'],
            ['title'=>'بلجرشي','city_id'=>'2'],
            ['title'=>'شرورة','city_id'=>'9'],
            ['title'=>'خباش','city_id'=>'9'],
            ['title'=>'حبونا','city_id'=>'9'],
            ['title'=>'ثار','city_id'=>'9'],
            ['title'=>'بدر الجنوب','city_id'=>'9'],
            ['title'=>'عتود','city_id'=>'10'],
            ['title'=>'الشقيق','city_id'=>'10'],
            ['title'=>'السادلية','city_id'=>'10'],
            ['title'=>'الأثلية','city_id'=>'10'],
            ['title'=>'هروب','city_id'=>'10'],
            ['title'=>'ضمد','city_id'=>'10'],
            ['title'=>'صامطة','city_id'=>'10'],
            ['title'=>'بيش','city_id'=>'10'],
            ['title'=>'العيدابي','city_id'=>'10'],
            ['title'=>'العارضة','city_id'=>'10'],
            ['title'=>'الطوال','city_id'=>'10'],
            ['title'=>'الريث','city_id'=>'10'],
            ['title'=>'الدرب','city_id'=>'10'],
            ['title'=>'الدائر','city_id'=>'10'],
            ['title'=>'الحرث','city_id'=>'10'],
            ['title'=>'أحد المسارحة','city_id'=>'10'],
            ['title'=>'فيفا','city_id'=>'10'],
            ['title'=>'جزر فرسان','city_id'=>'10'],
            ['title'=>'أبو عريش','city_id'=>'10'],
            ['title'=>'طريف','city_id'=>'3'],
            ['title'=>'رفحاء','city_id'=>'3'],
            ['title'=>'قفار','city_id'=>'11'],
            ['title'=>'الشنان','city_id'=>'11'],
            ['title'=>'سميراء','city_id'=>'11'],
            ['title'=>'مسجد لبدة','city_id'=>'11'],
            ['title'=>'الحائط','city_id'=>'11'],
            ['title'=>'جبة','city_id'=>'11'],
            ['title'=>'ثويليل','city_id'=>'11'],
            ['title'=>'بقعاء','city_id'=>'11'],
            ['title'=>'النحيتية','city_id'=>'11'],
            ['title'=>'تربة','city_id'=>'11'],
            ['title'=>'القاعد','city_id'=>'11'],
            ['title'=>'الغزالة','city_id'=>'11'],
            ['title'=>'الشملي','city_id'=>'11'],
            ['title'=>'الروضة','city_id'=>'11'],
            ['title'=>'الحفير','city_id'=>'11'],
            ['title'=>'البدع','city_id'=>'6'],
            ['title'=>'تيماء','city_id'=>'6'],
            ['title'=>'حقل','city_id'=>'6'],
            ['title'=>'أملج','city_id'=>'6'],
            ['title'=>'ضباء','city_id'=>'6'],
            ['title'=>'الوجه','city_id'=>'6'],
            ['title'=>'البرك','city_id'=>'5'],
            ['title'=>'الربوعة','city_id'=>'5'],
            ['title'=>'وادي بن هشبل','city_id'=>'5'],
            ['title'=>'مركز بللحمر','city_id'=>'5'],
            ['title'=>'محايل عسير','city_id'=>'5'],
            ['title'=>'تثليث','city_id'=>'5'],
            ['title'=>'بيشة','city_id'=>'5'],
            ['title'=>'قنا','city_id'=>'5'],
            ['title'=>'قصر ذهبان','city_id'=>'5'],
            ['title'=>'عبس','city_id'=>'5'],
            ['title'=>'ظهران الجنوب','city_id'=>'5'],
            ['title'=>'ظهران الجنوب','city_id'=>'5'],
            ['title'=>'سراة عبيدة','city_id'=>'5'],
            ['title'=>'سبت العلاية','city_id'=>'5'],
            ['title'=>'خاط','city_id'=>'5'],
            ['title'=>'حجلا','city_id'=>'5'],
            ['title'=>'تنومة','city_id'=>'5'],
            ['title'=>'تندحة','city_id'=>'5'],
            ['title'=>'بللسمر','city_id'=>'5'],
            ['title'=>'بارق','city_id'=>'5'],
            ['title'=>'باحة ربيعة','city_id'=>'5'],
            ['title'=>'القوباء','city_id'=>'5'],
            ['title'=>'الحرجة','city_id'=>'5'],
            ['title'=>'البرك','city_id'=>'5'],
            ['title'=>'أحد ثربان','city_id'=>'5'],
            ['title'=>'آل فيصل','city_id'=>'5'],
            ['title'=>'ختبة','city_id'=>'5'],
            ['title'=>'عقلة الصقور','city_id'=>'1'],
            ['title'=>'ضرية','city_id'=>'1'],
            ['title'=>'حرب الجلاس','city_id'=>'1'],
            ['title'=>'الشماسية','city_id'=>'1'],
            ['title'=>'رياض الخبراء','city_id'=>'1'],
            ['title'=>'عيون الجواء','city_id'=>'1'],
            ['title'=>'النبهانية','city_id'=>'1'],
            ['title'=>'الأسياح','city_id'=>'1'],
            ['title'=>'البدائع','city_id'=>'1'],
            ['title'=>'البكرية','city_id'=>'1'],
            ['title'=>'المذنب','city_id'=>'1'],
            ['title'=>'عنيزة','city_id'=>'1'],
            ['title'=>'العيص','city_id'=>'7'],
            ['title'=>'وادي الفرع','city_id'=>'7'],
            ['title'=>'ام المخاييل','city_id'=>'7'],
            ['title'=>'مهد الذهب','city_id'=>'7'],
            ['title'=>'خيبر','city_id'=>'7'],
            ['title'=>'العلا','city_id'=>'7'],
            ['title'=>'قرية العليا','city_id'=>'12'],
            ['title'=>'القطيف','city_id'=>'12'],
            ['title'=>'العديد','city_id'=>'12'],
            ['title'=>'الخفجي','city_id'=>'12'],
            ['title'=>'بقيق','city_id'=>'12'],
            ['title'=>'النعيرية','city_id'=>'12'],
            ['title'=>'سيهات','city_id'=>'12'],
            ['title'=>'رأس تنورة','city_id'=>'12'],
            ['title'=>'حفر الباطن','city_id'=>'12'],
            ['title'=>'الهفوف','city_id'=>'12'],
            ['title'=>'القيصومية','city_id'=>'12'],
            ['title'=>'العيون','city_id'=>'12'],
            ['title'=>'الأحساء','city_id'=>'12'],
            ['title'=>'ميسان','city_id'=>'13'],
            ['title'=>'مستورة','city_id'=>'13'],
            ['title'=>'العرضيات','city_id'=>'13'],
            ['title'=>'مركز كنانة','city_id'=>'13'],
            ['title'=>'العرضيات','city_id'=>'13'],
            ['title'=>'العرضيات','city_id'=>'13'],
            ['title'=>'رنية','city_id'=>'13'],
            ['title'=>'دوقة','city_id'=>'13'],
            ['title'=>'خليص','city_id'=>'13'],
            ['title'=>'حلي','city_id'=>'13'],
            ['title'=>'ثريبان العرضيات','city_id'=>'13'],
            ['title'=>'ثربان','city_id'=>'13'],
            ['title'=>'تربة','city_id'=>'13'],
            ['title'=>'بلدة الحبيل','city_id'=>'13'],
            ['title'=>'بحرة','city_id'=>'13'],
            ['title'=>'الهداء','city_id'=>'13'],
            ['title'=>'الموية','city_id'=>'13'],
            ['title'=>'المضيلف','city_id'=>'13'],
            ['title'=>'الليث','city_id'=>'13'],
            ['title'=>'الكامل','city_id'=>'13'],
            ['title'=>'القنفذة','city_id'=>'13'],
            ['title'=>'القوز','city_id'=>'13'],
            ['title'=>'الغالة','city_id'=>'13'],
            ['title'=>'الصهوة','city_id'=>'13'],
            ['title'=>'السعدية','city_id'=>'13'],
            ['title'=>'الخرمة','city_id'=>'13'],
            ['title'=>'الحوية','city_id'=>'4'],
            ['title'=>'البيضاء','city_id'=>'13'],
            ['title'=>'أضم','city_id'=>'13'],
            ['title'=>'أحد بني زايد','city_id'=>'13'],
            ['title'=>'حوطة سدير','city_id'=>'4'],
            ['title'=>'تمير','city_id'=>'4'],
            ['title'=>'الحلوة','city_id'=>'4'],
            ['title'=>'المزاحمية','city_id'=>'4'],
            ['title'=>'السليل','city_id'=>'4'],
            ['title'=>'روضة سدير','city_id'=>'4'],
            ['title'=>'وادي الدواسر','city_id'=>'4'],
            ['title'=>'مرات','city_id'=>'4'],
            ['title'=>'الدلم','city_id'=>'4'],
            ['title'=>'الأحساء','city_id'=>'12'],
            ['title'=>'السد','city_id'=>'5'],
            ['title'=>'الخالدية','city_id'=>'5'],
            ['title'=>'العزيزية','city_id'=>'5'],
            ['title'=>'النزهة','city_id'=>'5'],
            ['title'=>'الخشع','city_id'=>'5'],
            ['title'=>'السادلية','city_id'=>'10'],
            ['title'=>'الروضة','city_id'=>'3'],
            ['title'=>'الصناعية','city_id'=>'3'],
            ['title'=>'الورود','city_id'=>'3'],
            ['title'=>'الخليج','city_id'=>'3'],
            ['title'=>'الصالحية','city_id'=>'3'],
            ['title'=>'الروابي','city_id'=>'3'],
            ['title'=>'النسيم','city_id'=>'3'],
            ['title'=>'الصناعية','city_id'=>'3'],
            ['title'=>'قفار','city_id'=>'11'],
            ['title'=>'رواق','city_id'=>'1'],
            ['title'=>'وسط المدينة','city_id'=>'2'],
            ['title'=>'رواق','city_id'=>'1'],
            ['title'=>'المزاحمية','city_id'=>'4'],
            ['title'=>'بحرة','city_id'=>'13'],
            ['title'=>'الرونة','city_id'=>'5'],
            ['title'=>'العزيزية','city_id'=>'5'],
            ];
            DB::table('districts')->insert($districts);
        

    }
}
